Update jenkins-config.yaml
Preview PR for reference.  "libraries" is deprecated, the new config element is "librarySources"
Other wise you get this error ```2022-05-09 18:22:16.417+0000 [id=33]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class org.boozallen.plugins.jte.init.governance.GovernanceTier : libraries.
Available attributes : configurationProvider, librarySources```

See the history of the update where this is changed here https://github.com/jenkinsci/templating-engine-plugin/commit/7fcfdb0dd77ac552653fb85cd13407aa19ff2ff8
File is src/main/groovy/org/boozallen/plugins/jte/init/governance/GovernanceTier.groovy